[global]
#pytest启用进程数量
number_of_threads = 2
#selenium忽略ssl报错
ignore_ssl_error = true
log_name = run_log
#虚拟机、磁盘等资源创建时前缀
res_create_pre = fullTest

[env]
env_url = https://10.16.204.131
username = admin
password = Pass@admin2024

[pytest]
addopts = -v -s -n 2 --alluredir=./result --clean-alluredir 
marks = 
    test1
    test2
    test3

log_cli = True
log_cli_level = ERROR
log_cli_format = %(asctime)s [%(levelname)s] | %(filename)s:%(lineno)s | %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S