[global]
#pytest启用进程数量
number_of_process = 1
#selenium忽略ssl报错
ignore_ssl_error = true
log_name = run_log
#虚拟机、磁盘等资源创建时前缀
res_create_pre = fullTest

[env]
env_url = https://10.16.204.125
username = admin
password = Pass@admin2024
x86_vcluster_name = X86默认集群
arm_vcluster_name = Aarch64默认集群
vm_temp_id = vmt-005e202111
iso_name = ubuntu-24.04-desktop-amd64.iso
iso_in_pool_name = ceph1
local_sp_id = 
wds_sp_id = 
xsky_sp_id = 
san_sp_id = 
nas_sp_id = 


[pytest]
testpath = D:\Desktop\work\SeAutoTest-1\test_cases\login_test
addopts = -v -s --alluredir=./result --clean-alluredir 
marks = test1
    test2
    test3

log_cli = True
log_cli_level = ERROR
log_cli_format = %(asctime)s [%(levelname)s] | %(filename)s:%(lineno)s | %(message)s
log_cli_date_format = %Y-%m-%d %H:%M:%S