[login]
username_input = //input[@name='username']
password_input = //input[@name='password']
login_button = //span[contains(text(), '登录')]

[page_head_index]
;系统上方菜单列，首页、计算、存储、网络、主机等元素
index_button = //span[text()='首页']
compute_button = //span[text()='计算']
storage_button = //span[text()='存储']
network_button = //span[text()='网络']
physical_button = //span[text()='主机']
vmware_button = //span[text()='VMware']
system_button = //span[text()='平台管理']
head_user_info = //span[@class='i-layout-header-user-name']
head_user_info_logout = //span[text()='退出登录']

[computer_head_index]
; 计算\虚拟机页面下子菜单列，虚拟机、虚拟机分组、模板、镜像等元素
instance_button = //div[@class='i-header-submenu']//span[text()='虚拟机']
resource_group_button = //div[@class='i-header-submenu']//span[text()='虚拟机分组']
vm_template_button = //div[@class='i-header-submenu']//span[text()='模板']
file_iso_button = //div[@class='i-header-submenu']//span[text()='镜像']
instance_backup_button = //div[@class='i-header-submenu']//span[text()='备份']
export_file_button = //div[@class='i-header-submenu']//span[text()='导出文件']

[computer_list_head]
; 虚拟机列表上方操作按钮，创建虚拟机、开机、关机、更多操作等元素
create_vm_button = //span[text()='创建虚拟机']
vm_on_button = //span[text()='开机']
vm_shutdown_button = //span[text()='关机']
more_action_button = //span[contains(text(), '更多操作')]
reboot_more_act_button = //div[@x-placement='bottom']//li[contains(text(), '重启')]
remote_login_head_button = //div[@x-placement='bottom']//li[text()='远程登录']
remote_vnc_head_button = //div[@x-placement='right']//li[contains(text(), '控制台-vnc')]

[general_common]
select_dropdown_pagination_pgdown = //div[contains(@class, 'ivu-select-dropdown')]//div[contains(@class, 'vxe-grid--pager-wrapper')]//li[contains(@title, '下一页')]
form_pagination = //div[contains(@class, 'ivu-card-body')]//div[contains(@class, 'vxe-grid--pager-wrapper')]
popup_list_pgdown = //div[@class='ivu-modal-header']/..//div[contains(@class, 'vxe-grid--pager-wrapper')]//li[contains(@title, '下一页')]

[vm_list]
; 替换虚拟机名称
vm_name_button = //div[@class='vxe-table--main-wrapper']//a[@class='bcc-link'][contains(text(),'<replace>')]
vm_id = //div[@class='vxe-table--main-wrapper']//a[@class='bcc-link'][contains(text(),'<replace>')]/../../../../../..
; 使用虚拟机ID执行检索，替换虚拟机ID
vm_stat = //div[@class='vxe-table--main-wrapper']//tr[@rowid='<replace>']//div[contains(@class, 'bcc-vm-status-tag')]//span[@class='bcc-vm-status-text']/span
vm_ip_address = (//div[@class='vxe-table--main-wrapper']//tr[@rowid='<replace>']//div[@class='vxe-cell']//span)[6]
vm_hw_size = //div[@class='vxe-table--main-wrapper']//tr[@rowid='<replace>']//div[contains(@class, 'bcc-vm-status-icon')]//span[@class='bcc-vm-status-text']/span
vm_host = (//div[@class='vxe-table--main-wrapper']//tr[@rowid='<replace>']//a[@class='bcc-link'])[2]
; 虚拟机列表下一页控件
list_pgdown = //div[contains(@class, 'bcc-split-flex-trigger')]//div[contains(@class, 'vxe-grid--pager-wrapper')]//li[contains(@title, '下一页')]

[create_vm]
; 虚拟机新建页面元素，新建虚拟机表单及相关元素，可选元素有：全新虚拟机、从模板部署、从备份部署
create_vm_method = //li[contains(text(), '<replace>')]
; create_vm_temp = //li[contains(text(), '从模板部署')]

vm_name_input = //input[@placeholder='请输入名称']
temp_selector = //div[@prop='srcTemplateId']//span[@class='ivu-select-selected-value']
; 依次替换模板ID、模板名称
temp_select_name = //tr[contains(@rowid, '<replace>')]//span[contains(text(), '<replace>')]
; 集群定位使用是应根据实际替换集群名称
vcluster_select_label = //label[text()='<replace>']
group_selector = //div[@prop='groupId']//span[@class='ivu-select-selected-value']
; 分组定位需要根据实际情况替换分组名称
group_select_name = //div[@class='lede-tree-node__label v-bcc-tooltip-ex']//span[text()='<replace>']
storage_selector = //div[@prop='poolId']//span[@class='ivu-select-selected-value']
; 需要根据实际替换存储名称
storage_select_name = //span[@class='vxe-cell--label'][text()='<replace>']
; 根据实际需要替换，可选项有：自动选择、指定主机
schedule_type_label = //label[contains(text(),'<replace>')]
schedule_choice_host = //div[@prop='expectedHost']//span[@class='ivu-select-selected-value']
; 根据实际需要替换为指定节点IP
schedule_choice_host_name = //tr[not(contains(@rowid, 'sp'))]//span[contains(text(), '<replace>')]

more_setup = //a[contains(text(),'更多配置')]/i
startup_setup_checkbox = //label[contains(text(),'创建完成自动开机')]//input
; 根据实际需要替换，可选项有：Linux、Windows
system_type = //label[normalize-space()='<replace>']
; 根据实际需要替换，可选项有：Legacy、UEFI
boot_type = //label[normalize-space()='<replace>']
remark_input = //textarea[@placeholder='请输入备注']

; 根据实际需要替换，可选项有：4核8GB、8核16GB、16核32GB
common_hardware_conf = //label[contains(text(),'<replace>')]
cpu_conf_button = //span[contains(text(), 'CPU')]/following-sibling::span//span
cpu_conf_input = //div[@prop='cpuCurrent']//input
cpu_conf_advanced = //a[@content='高级']
; 根据实际替换为下拉列表选择项
cpu_conf_socket_num_selector = (//div[@class='ivu-select-dropdown ivu-select-dropdown-transfer' and not(contains(@style, 'display: none'))])/ul[@class='ivu-select-dropdown-list']/li[contains(text(), '1')]
; 根据实际需求设置插槽数量
cpu_conf_socket_num = //li[contains(text(), '<replace>')]

memory_conf_button = //span[contains(text(), '内存')]/following-sibling::span//span
memory_conf_input = //div[@prop='memorySize']//input

; 根据实际替换为磁盘序号，如：磁盘1、磁盘2
disk_conf_button = //span[contains(text(), '<replace>')]/following-sibling::span//span
disk_conf_add_button = //span[contains(text(), '<replace>')]/following-sibling::span//i[contains(@class, 'bccfont-add-circle')]
disk_conf_reduce_button = //span[contains(text(), '<replace>')]/following-sibling::span//i[contains(@class, 'bccfont-minus-circle')]
; 根据实际替换为磁盘序号，1、2、3
disk_conf_input = (//div[@prop='volumeSize']//input)[<replace>]

; 根据实际替换为网卡序号，如：网卡1、网卡2
vmnic_conf_button = //span[contains(text(), '<replace>')]/following-sibling::span//span
; 序号为网卡序号，如：1、2、3
vmnic_conf_uplink_selector = (//div[@prop='uplinkDeviceId']//span[@class='ivu-select-selected-value'])[<replace>]
; 根据实际修改上行交换机名称
vmnic_conf_uplink_select_name = //span[@class='vxe-cell--label' and contains(text(), '<replace>')]
; 序号为网卡序号
vmnic_hwaddr_conf_input = (//div[@prop='hwAddr']//input)[<replace>]
; 序号为网卡序号
vmnic_firewall_conf_selector = (//div[@prop='firewallId']//span[@class='ivu-select-selected-value'])[<replace>]
; 根据实际情况替换为防火墙名称
vmnic_firewall_conf_select_name = //li[contains(text(),'<replace>')]
; 序号为网卡序号
vmnic_is_use_ipv4 = (//span[contains(text(), '启用IPv4')]/../following-sibling::div//span[contains(@class, 'ivu-switch-small')])[<replace>]
vmnic_ipv4_conf_input = (//input[contains(@placeholder, '输入IPv4地址')])[<replace>]
vmnic_ipv4_conf_prefix_input = (//div[@prop='netMask']//input)[<replace>]
vmnic_ipv4_conf_gateway_input = (//div[@prop='gatewayIp']//input)[<replace>]
vmnic_conf_advanced = (//a[contains(text(), '高级选项')]/i)[<replace>]
vmnic_conf_is_online_radio = (//label[contains(text(), '上线')]//input)[<replace>]
vmnic_conf_offline_radio = (//label[contains(text(), '下线')]//input)[<replace>]
vmnic_conf_ipcheck_checkbox = (//label[contains(text(), '开启IP地址检查')])[<replace>]
vmnic_conf_in_bandwidth_checkbox = (//div[@prop='inBandwidth']//label[contains(text(), '启用')]//input)[<replace>]
vmnic_conf_in_bandwidth_input = (//div[@prop='inBandwidth']//label[contains(text(), '启用')]/following-sibling::span//input)[<replace>]
vmnic_conf_out_bandwidth_checkbox = (//div[@prop='outBandwidth']//label[contains(text(), '启用')]//input)[<replace>]
vmnic_conf_out_bandwidth_input = (//div[@prop='outBandwidth']//label[contains(text(), '启用')]/following-sibling::span//input)[<replace>]
vmnic_conf_queues_checkbox = (//div[@prop='queues']//label[contains(text(), '启用')]//input)[<replace>]
vmnic_conf_queues_selector = (//div[@prop='queues']//span[@class='ivu-select-selected-value'])[<replace>]
vmnic_conf_queues_select_name = (//div[@class='ivu-select-dropdown ivu-select-dropdown-transfer' and not(contains(@style, 'display'))])/ul[@class='ivu-select-dropdown-list']/li[contains(text(), '<replace>')]
vmnic_add_button = //span[contains(text(), '<replace>')]/following-sibling::span//i[contains(@class, 'bccfont-add-circle')]
vmnic_reduce_button = //span[contains(text(), '<replace>')]/following-sibling::span//i[contains(@class, 'bccfont-minus-circle')]


; 根据实际替换为光驱序号
optical_driver_button = //span[contains(text(), '<replace>')]
optical_driver_selector = (//input[@placeholder='文件类型：iso'])[<replace>]/../..//button
; 平台内部镜像选择，需要依次替换入：存储池名称、iso名称
optical_driver_select_name = //div[@class='vxe-table--main-wrapper']//a[text()='<replace>']//..//..//preceding-sibling::td[3]//span[text()='<replace>']
;两个光驱位置使用时需要根据实际修改序号
optical_driver_input = (//input[@placeholder='文件类型：iso'])[<replace>]
optical_driver_submit = (//div[@class='ivu-modal-footer']//div//span[contains(text(),'确定')])[<replace>]

add_hw_button = //a[contains(text(), '添加硬件')]
add_hw_disk_button = //li[contains(text(),'磁盘')]
add_hw_vmnic_button = //li[contains(text(),'网卡')]
add_hw_usb_button = //li[contains(text(),'USB')]
add_hw_gpu_button = //li[contains(text(),'GPU')]

; 需要根据实际需求修改USB序号,如USB1、USB2
usb_conf_button = //span[contains(text(), '<replace>')]/following-sibling::span//span
; 根据实际修改USB序号，如：1、2、3
usb_conf_selector = (//div[@prop='usbId']//i[contains(@class, 'ivu-icon-ios-arrow-down')])[<replace>]
; 根据实际需要修改指定的USB设备ID
usb_conf_select_name = //span[@class='vxe-cell--label' and contains(text(), '<replace>')]

; 根据实际需求修改GPU序号
gpu_conf_button = //span[contains(text(), '<replace>')]/following-sibling::span//span
gpu_conf_selector = (//div[@prop='pciId']//i[contains(@class, 'ivu-icon-ios-arrow-down')])[<replace>]
; TODO:补充GPU定位
gpu_conf_select_name = 

vm_conf_summarize_name = //span[@class='bcc-descriptions-item__label has-colon '][contains(text(),'名称')]/following-sibling::span/div
vm_conf_summarize_hw = //span[@class='bcc-descriptions-item__label has-colon '][contains(text(),'配置')]/following-sibling::span/span
vm_conf_summarize_group = //span[@class='bcc-descriptions-item__label has-colon '][contains(text(),'分组')]/following-sibling::span/span
vm_conf_summarize_system_kind = //span[@class='bcc-descriptions-item__label has-colon '][contains(text(),'平台')]/following-sibling::span/span
vm_conf_summarize_create_nums_input = //span[@class='mr-sm']/following-sibling::div//input
vm_conf_summarize_create_nums_add = (//span[@class='mr-sm']/following-sibling::div//i)[2]
vm_conf_summarize_create_nums_reduce = (//span[@class='mr-sm']/following-sibling::div//i)[1]

vm_create_button = //span[text()='创建']
vm_create_cancel_button = //button[contains(@class, 'mr-sm')]//span[text()='取消']

[vm_hw_conf_details]
head_name_and_id = (//div[@class='ivu-page-header-title'])[1]
overview_button = (//div[@class='ivu-tabs-tab'][contains(text(),'概览')])[2]
