[login]
username_input = //input[@name='username']
username_input_find_by = XPATH
password_input = //input[@name='password']
password_input_find_by = XPATH
login_button = //span[text()='登录 ']
login_button_find_by = XPATH

[page_head_index]
#系统上方菜单列，首页、计算、存储、网络、主机等元素
index_button = //span[text()='首页']
index_button_find_by = XPATH
compute_button = //span[text()='计算']
compute_button_find_by = XPATH
storage_button = //span[text()='存储']
storage_button_find_by = XPATH
network_button = //span[text()='网络']
network_button_find-by = XPATH
physical_button = //span[text()='主机']
physical_button_find_by = XPATH
vmware_button = //span[text()='VMware']
vmware_button_find_by = XPATH
system_button = //span[text()='平台管理']
system_button_find_by = XPATH
head_user_info = //span[@class='i-layout-header-user-name']
head_user_info_find_by = XPATH
head_user_info_logout = //span[text()='退出登录']
head_user_info_logout_find_by = XPATH

[computer_head_index]
#计算\虚拟机页面下子菜单列，虚拟机、虚拟机分组、模板、镜像等元素
instance_button = //div[@class='i-header-submenu']//span[text()='虚拟机']
instance_button_find_by = XPATH
resource_group_button = //div[@class='i-header-submenu']//span[text()='虚拟机分组']
resource_group_button_find_by = XPATH
vm_template_button = //div[@class='i-header-submenu']//span[text()='模板']
vm_template_button_find_by = XPATH
file_iso_button = //div[@class='i-header-submenu']//span[text()='镜像']
file_iso_button_find_by = XPATH
instance_backup_button = //div[@class='i-header-submenu']//span[text()='备份']
instance_backup_button_find_by = XPATH
export_file_button = //div[@class='i-header-submenu']//span[text()='导出文件']
export_file_button_find_by = XPATH

[computer_list_head]
#虚拟机列表上方操作按钮，创建虚拟机、开机、关机、更多操作等元素
create_vm_button = //span[text()='创建虚拟机']
create_vm_button_find_by = XPATH
vm_on_button = //span[text()='开机']
vm_on_button_find_by = XPATH
vm_shutdown_button = //span[text()='关机']
vm_shutdown_button_find_by = XPATH
more_action_button = //span[text()=' 更多操作 ']
more_action_button_find_by = XPATH
reboot_more_act_button = //div[@x-placement='bottom']//li[text()='重启 ']
reboot_more_act_button_find_by = XPATH
remote_login_head_button = //div[@x-placement='bottom']//li[text()='远程登录']
remote_login_head_button_find_by = XPATH
remote_vnc_head_button = //div[@x-placement='right']//li[text()=' 控制台-VNC ']
remote_vnc_head_button_find_by = XPATH
